version: 2

# Set the OS, Python version and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: dirhtml
  configuration: docs/conf.py
  fail_on_warning: false

# Explicitly set the version of Python and requirements
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

# Build PDF & ePub
formats:
  - epub
  - pdf
  - htmlzip
